"""rename table

Revision ID: 51db6dc029e8
Revises: 8f96348a76ba
Create Date: 2020-07-30 00:37:10.295979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51db6dc029e8'
down_revision = '8f96348a76ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TagModelTable',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Tag', sa.String(length=128), nullable=False),
    sa.Column('DateAddedUtc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Tag')
    )
    op.create_table('UserModelTable',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=32), nullable=False),
    sa.Column('Salt', sa.String(length=32), nullable=False),
    sa.Column('Hash', sa.String(length=128), nullable=False),
    sa.Column('Token', sa.String(length=32), nullable=True),
    sa.Column('RegistrationDateUtc', sa.DateTime(), nullable=True),
    sa.Column('LoginDateUtc', sa.DateTime(), nullable=True),
    sa.Column('ExpiryDateUtc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('BlogModelTable',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AuthorId', sa.Integer(), nullable=True),
    sa.Column('Title', sa.String(length=128), nullable=False),
    sa.Column('Text', sa.Text(), nullable=True),
    sa.Column('LastUpdateDateUtc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AuthorId'], ['UserModelTable.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('BlogTagAssociationTable',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('BlogId', sa.Integer(), nullable=True),
    sa.Column('TagId', sa.Integer(), nullable=True),
    sa.Column('DateAddedUtc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BlogId'], ['BlogModelTable.Id'], ),
    sa.ForeignKeyConstraint(['TagId'], ['TagModelTable.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('BlogModel')
    op.drop_table('UserModel')
    op.drop_table('TagModel')
    op.drop_table('BlogTagAssociation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BlogTagAssociation',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('BlogId', sa.INTEGER(), nullable=True),
    sa.Column('TagId', sa.INTEGER(), nullable=True),
    sa.Column('DateAddedUtc', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['BlogId'], ['BlogModel.Id'], ),
    sa.ForeignKeyConstraint(['TagId'], ['TagModel.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('TagModel',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('Tag', sa.VARCHAR(length=128), nullable=False),
    sa.Column('DateAddedUtc', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Tag')
    )
    op.create_table('UserModel',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('Username', sa.VARCHAR(length=32), nullable=False),
    sa.Column('Salt', sa.VARCHAR(length=32), nullable=False),
    sa.Column('Hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('Token', sa.VARCHAR(length=32), nullable=True),
    sa.Column('RegistrationDateUtc', sa.DATETIME(), nullable=True),
    sa.Column('LoginDateUtc', sa.DATETIME(), nullable=True),
    sa.Column('ExpiryDateUtc', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('BlogModel',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('AuthorId', sa.INTEGER(), nullable=True),
    sa.Column('Title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('Text', sa.TEXT(), nullable=True),
    sa.Column('LastUpdateDateUtc', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['AuthorId'], ['UserModel.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('BlogTagAssociationTable')
    op.drop_table('BlogModelTable')
    op.drop_table('UserModelTable')
    op.drop_table('TagModelTable')
    # ### end Alembic commands ###
